[package]
name = "simple_blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
bcs = "0.1.6"
ed25519-dalek = { version = "2.2.0", features = ["serde", "rand_core"] }
hex = "0.4.3"
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
sha2 = "0.10.9"
